#!/bin/sh

set -e

ACCUEIL_cmdname=${0##*/}

usage()
{
    cat << USAGE >&2
Usage:
    $ACCUEIL_cmdname COMMAND

Commands:
    service     Start application service.
    version     Show version information.
USAGE
    exit 1
}

service()
{
    : "Cleanup ..." && {
        php artisan cache:clear --quiet --no-interaction
        php artisan config:clear --quiet --no-interaction
        php artisan route:clear --quiet --no-interaction
        php artisan view:clear --quiet --no-interaction
    }

    : "Initialize ..." && {
        php artisan package:discover --quiet --no-interaction
        php artisan storage:link --quiet --no-interaction

        if [ "${APP_ENV:=""}" = "production" ]; then
            php artisan config:cache --quiet --no-interaction
            php artisan route:cache --quiet --no-interaction
            php artisan view:cache --quiet --no-interaction
        fi
    }
}

version()
{
    cat << VERSION >&2
Application
    base: $(php "${APP_ROOT}/artisan" --version)

PHP
$(php-fpm -v | sed "s/^/    /g")

Nginx
$(nginx -v 2>&1 | sed "s/^/    /g")
VERSION
    exit
}

# process arguments
while [[ $# -gt 0 ]]
do
    case "$1" in
        service )
        service
        exec php-fpm \
            & exec nginx -g "daemon off;"
        ;;
        version )
        version
        ;;
        "" )
        usage
        ;;
        --help)
        usage
        ;;
        *)
        exec "$@"
        ;;
    esac
done
